# Generated by Django 5.0.8 on 2024-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='detal_by_english',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_english',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
