# Generated by Django 5.0.8 on 2024-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_alter_serviceprovideroffer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_service',
            name='file',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
