# Generated by Django 5.0.8 on 2024-12-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_services_detal_by_english_services_name_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='username',
            field=models.CharField(max_length=400),
        ),
    ]
