# Generated by Django 5.0.8 on 2024-12-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_alter_cuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrating',
            name='rating',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
