# Generated by Django 5.0.4 on 2024-09-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_alter_order_service_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovideroffer',
            name='time_arrive',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
