# Generated by Django 5.0.8 on 2024-12-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0004_alter_clientrating_rating_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrating',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
