# Generated by Django 5.0.4 on 2024-09-14 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0004_serviceprovideroffer_time_arrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfications_broviders',
            name='brovider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
