# Generated by Django 5.0.8 on 2024-12-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_alter_clientrating_rating_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_service',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('offer', 'offer'), ('Complete', 'Complete')], default='p', max_length=100),
        ),
    ]
