# Generated by Django 5.0.4 on 2024-09-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_alter_notfications_broviders_brovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brovides_services',
            name='rating',
            field=models.FloatField(default=3),
        ),
    ]
