# Generated by Django 5.0.4 on 2024-09-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0006_alter_brovides_services_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
