# Generated by Django 5.0.8 on 2024-12-26 01:55

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0006_alter_order_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notfications_broviders',
            name='content_english',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notfications_broviders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notfications_broviders',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notfications_broviders',
            name='title_english',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notfications_client',
            name='content_english',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notfications_client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 26, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notfications_client',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notfications_client',
            name='title_english',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
