# Generated by Django 5.0.4 on 2024-09-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0007_cuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
