# Generated by Django 5.0.8 on 2024-12-26 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0007_notfications_broviders_content_english_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_offer_from_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.order_service')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.brovides_services')),
            ],
        ),
    ]
