# Generated by Django 5.0.8 on 2025-03-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0008_send_offer_from_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
