# Generated by Django 5.0.4 on 2024-09-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0009_order_service_descrtion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='serviceprovideroffer',
            constraint=models.UniqueConstraint(fields=('order', 'provider'), name='unique_provider_offer_per_order'),
        ),
    ]
