# Generated by Django 5.0.8 on 2025-03-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0009_alter_cuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='fcm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FCM Token'),
        ),
    ]
