# Generated by Django 5.0.8 on 2025-03-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0010_cuser_fcm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brovides_services',
            options={'verbose_name': 'Provided Service', 'verbose_name_plural': 'Provided Services'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='order_service',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
