# Generated by Django 5.0.4 on 2024-09-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0010_serviceprovideroffer_unique_provider_offer_per_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='brovides_services',
            name='indebtedness',
            field=models.IntegerField(default=0),
        ),
    ]
