# Generated by Django 5.0.8 on 2025-11-24 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0011_alter_brovides_services_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_service',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user_data.order_service')),
            ],
            options={
                'verbose_name': 'Order File',
                'verbose_name_plural': 'Order Files',
            },
        ),
    ]
