# Generated by Django 5.0.4 on 2024-09-25 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0012_alter_brovides_services_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brovides_services',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.services'),
        ),
        migrations.AlterField(
            model_name='brovides_services',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
