# Generated by Django 5.0.4 on 2024-09-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0013_alter_brovides_services_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brovides_services',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
