# Generated by Django 5.0.4 on 2024-10-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0014_brovides_services_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brovides_services',
            name='debt_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
